# Generated by Django 4.2.7 on 2023-11-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_addpets_addpet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpet',
            name='text',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
