# Generated by Django 4.2.7 on 2023-11-02 13:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_rename_post_addpets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addPets',
            new_name='addPet',
        ),
    ]
