# Generated by Django 4.2.7 on 2023-11-02 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0004_alter_addpet_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addPet',
            new_name='Pets',
        ),
    ]
