# Generated by Django 4.2.7 on 2023-11-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_rename_pets_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='text',
            field=models.TextField(verbose_name='Place '),
        ),
    ]
