# Generated by Django 4.2.7 on 2023-11-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_pet_description_alter_pet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
