# Generated by Django 4.2.7 on 2023-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='text',
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pet',
            name='place',
            field=models.TextField(default=''),
        ),
    ]
